### PR TITLE
Add uniqueness check & fix auto ci build issue & Add unit tests

### LINKED ISSUE #10: add Lib proper structure
https://github.com/Anastasia-Labs/direct-order-contracts/blob/97640a159de63b09f73cbb91dfc2538c7465e0e0/direct-order.cabal#L97-L101

```
library
  import: lang, dependencies
  exposed-modules:
    Order
    Utils
  hs-source-dirs: src
```

### PR DESCRIPTION
**Pull request by nikhils9**
Refs: #5 #2

### CODE REVIEW

File: src/Order.hs [hunk 1]
```diff
@@ -136,15 +138,35 @@ porderSuccessor foldCount orderInput orderOutput = unTermCont $ do
       (foldCount + 1)
       perror
 
+puniqueOrderedTxOuts :: Term s ((PBuiltinList (PAsData PInteger)) :--> (PInteger :--> PTxOut) :--> (PBuiltinList PTxOut))
+puniqueOrderedTxOuts =
```
Comment (colll78) [inline src/Order.hs:163]: looks good, but lift the elemAt parameter into an outer lambda to avoid redundantly passing it in every recursive call.

For example:
```
pfind :: PIsListLike l a => Term s ((a :--> PBool) :--> l a :--> PMaybe a)
pfind = phoistAcyclic $ plam $ \f ->
   (pfix #$ plam $ \self xs ->
    pelimList
      ( \y ys ->
          pif
            (f # y)
            (pcon $ PJust y)
            (self # ys)
      )
      (pcon PNothing)
      xs
    )
```

**Review by solidsnakedev — APPROVED** [review]
